-- ESC 통계 백엔드 스키마  (Supabase project ref: nxyahagtfnlrsegvjxgi)
-- 익명 세션 수집 + 개인행 비노출 상위 N% 백분위 RPC.
-- 2026-06-11 라이브 DB에서 추출해 박제(레포 재현용). 비의료·PII 없음.
-- 기존엔 Management API로 즉석 생성돼 레포에 기록이 없었음 → 본 파일로 버전관리.

-- ── 익명 세션 이벤트 테이블 ──────────────────────────────
create table if not exists public.esc_sessions (
  id          bigint generated by default as identity primary key,
  anon_id     text not null,            -- 가명 UUID(esc_anon_id), PII 아님
  nickname    text,                     -- 사용자 입력 별명(선택)
  game        text,                     -- cheonggi/nback/schulte/flanker/stroop/brave/grit/persist/calm/listening
  mode        text,                     -- focus/speed/challenge/grit/calm/listening
  accuracy    numeric,                  -- overallAccuracy 0~1
  payload     jsonb,                    -- 원본 이벤트 레코드 전체
  created_at  timestamptz not null default now()
);

create index if not exists esc_sessions_game_idx    on public.esc_sessions (game);
create index if not exists esc_sessions_anon_idx    on public.esc_sessions (anon_id);
create index if not exists esc_sessions_created_idx on public.esc_sessions (created_at);

-- ── RLS: anon은 INSERT만 (SELECT/UPDATE/DELETE 불가 → 개인행 비노출) ──
alter table public.esc_sessions enable row level security;

drop policy if exists "esc anon insert" on public.esc_sessions;
create policy "esc anon insert"
  on public.esc_sessions
  for insert
  to anon
  with check (true);

-- ── 상위 N% 백분위 (SECURITY DEFINER = 개인행 안 보이고 집계만 반환) ──
-- 유저별 best accuracy 기준 순위. 표본 < 2명이면 null. 하한 1%.
create or replace function public.esc_top_percent(p_anon text, p_game text default null)
returns numeric
language sql
security definer
set search_path to 'public'
as $$
  with per_user as (
    select anon_id, max(accuracy) as best
    from public.esc_sessions
    where accuracy is not null and (p_game is null or game = p_game)
    group by anon_id
  ), me as (select best from per_user where anon_id = p_anon)
  select case
    when (select count(*) from per_user) < 2 or not exists(select 1 from me) then null
    else greatest(1, round(100.0 * (select count(*) from per_user where best > (select best from me)) / (select count(*) from per_user), 0))
  end;
$$;

-- anon 역할이 RPC 실행 가능하도록
grant execute on function public.esc_top_percent(text, text) to anon;
